version: '3'

services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - /media/zero/T7/configs/homarr/configs:/app/data/configs
      - /media/zero/T7/configs/homarr/icons:/app/public/icons
      - /media/zero/T7/configs/homarr/data:/data
    ports:
      - '7575:7575'


  qbittorrent:
    container_name: qbittorrent
    image: ghcr.io/hotio/qbittorrent:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
      - WEBUI_PORTS=8080/tcp,8080/udp
    volumes:
      - /media/zero/T7/configs/qbitconfig:/config
      - /media/zero/T7/Media/movies:/data

  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - /media/zero/T7/configs/delugeconfig:/config
      - /media/zero/T7/Media/tv:/downloads
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
      - 58846:58846 #optional
    restart: unless-stopped


  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /media/zero/T7/configs/sonarrconfig:/config
      - /media/zero/T7/Media/downloads:/downloads #optional
      - /media/zero/T7/Media/tv:/tv #optional
      - /media/zero/T7/Media/anime:/anime #optional
    ports:
      - 8989:8989
    restart: unless-stopped


  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /media/zero/T7/configs/radarrconfig:/config
      - /media/zero/T7/Media/movies:/movies #optional
      - /media/zero/T7/Media/downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped


  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /media/zero/T7/configs/jellyconfig:/config
      - /media/zero/T7/Media/tv:/data/tvshows
      - /media/zero/T7/Media/movies:/data/movies
      - /media/zero/T7/Media/anime:/data/anime
    ports:
      - 8096:8096
    restart: unless-stopped


  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /media/zero/T7/configs/prowlarrconfig:/config
    ports:
      - 9696:9696
    restart: unless-stopped


  jellyseerr:
    container_name: jellyseerr
    image: ghcr.io/hotio/jellyseerr
    ports:
      - "5055:5055"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
    volumes:
      - /media/zero/T7/configs/jellyseerrconfig:/config
